routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('tree', 'TreeController');

Route::get('tree/{tree}', 'TreeController@getImg')->name('tree.getImg');

app/Species.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Species extends Model
{
    protected $fillable = [
        'name','one','two','three',
    ];

    public function trees(){
    	return $this->hasMany('App\Tree');
    }
}

app/Tree.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Tree extends Model
{
    protected $fillable = [
        'name', 'height', 'amount', 'specie_id', 'user_id',
    ];

    public function species(){
    	return $this->belongsTo('App\Species', 'id', 'specie_id');
    }

    public function user(){
    	return $this->belongsTo('App\User');
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'identification','name','lastname','direction','country','telephone','email', 'password','admin',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function trees(){
        return $this->hasMany('App\Tree');
    }


}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;
use Illuminate\Http\Request;
use Auth;
use App\Species;
use App\Tree;
use App\User;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
         $tableUsers = \DB::table('trees')
        ->join('species', 'trees.specie_id', '=', 'species.id')
        ->join('users', 'trees.user_id', '=', 'users.id')
        ->select('trees.name',\DB::raw("CONCAT(users.name,' ',users.lastname) as fullname"),'trees.height','species.name as speciesname','trees.id as id','trees.specie_id')
        ->get();

         $trees =  \DB::table('trees')
        ->join('species', 'trees.specie_id', '=', 'species.id')
        ->join('users', 'trees.user_id', '=', 'users.id')
        ->select('trees.name','trees.height','species.name as speciesname','trees.specie_id')
        ->where('trees.user_id', Auth::user()->id)
        ->get();

         $cantUsers = \DB::table('users')->select(\DB::raw('count(*) as cantu'))->where('admin', false)->get();
         $cantTrees = \DB::table('trees')->select(\DB::raw('count(*) as cantt'))->get();
         $species = Species::all();
         return view('home',compact('species','trees','cantUsers','cantTrees','tableUsers'));

    }

   
}

app/Http/Controllers/TreeController.php
<?php

namespace App\Http\Controllers;
use App\Tree;
use App\User;
use App\Species;
use Redirect;
use Auth;
use Illuminate\Http\Request;

class TreeController extends Controller
{


    

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {    
         
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
      
       
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {   
     
        Tree::create([
           
            'name' => $request['nom'],
            'height'=>1,
            'amount'=>$request['monto'],
            'specie_id'=>$request['combo'],
            'user_id'=>Auth::user()->id,
        ]);
        
        return Redirect()->route('home');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \home
     */
    public function show($id)
    {
       
        $informations = \DB::table('trees')
        ->join('species', 'trees.specie_id', '=', 'species.id')
        ->select('trees.name','trees.height','species.name')
        ->where('species.id', $id)
        ->get();
       
       
       return view('home',compact('informations'));
    }

    /**
    *regarding the id he  will return a user
    *
    * @param int $id
    */
    public function getImg($id)
    {
       
        $imgs = \DB::table('species')
        ->select('one as imgone','two as imgtwo','three as imgthree')
        ->where('id', $id)
        ->get();
       
       
       return view('photo',compact('imgs'));
    }
    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $trees =  \DB::table('trees')
        ->join('species', 'trees.specie_id', '=', 'species.id')
        ->join('users', 'trees.user_id', '=', 'users.id')
        ->select('trees.name','trees.height','trees.id as id')
        ->where('trees.id', $id)
        ->get();
        
        return view('edit',compact('trees'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $updateTree = request()->except(['_token','_method']);
        Tree::where('id','=',$id)->update($updateTree);
        return Redirect()->route('home');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
       
    }
}

resources/views/edit.blade.php
@extends('layouts.app')
<style>
            html, body {
                background-image: url('/img/client.jpg');
                font-family: 'Numans', sans-serif;
            }

</style>

@section('content')

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card"  style="background-color: rgba(0,0,0,0.5); color: #fff; width:110%; height: 110%;margin-top:7%; ">
                <div class="card-header" style="text-align: center; font-size:22px;">{{ __('Edit Tree') }}</div>

                <div class="card-body"style="margin-right:10%; margin-top:4%;">
                             
                             @foreach ($trees as $tree)      
                            <form action="{{ url('/tree/'. $tree->id) }}" method="post" enctype="multipart/form-data"> 
							   @csrf
							   @method('PATCH')
                               
                                  
                                <input type="number" name="height" id="altura" placeholder=" Altura " onfocus="this.placeholder = ''" onblur="this.placeholder = ' Altura '" required="" value="{{ $tree->height }}" >

                                <input type="text" name="name" id="especie" placeholder=" Nombre Del Árbol " onfocus="this.placeholder = ''" onblur="this.placeholder = ' Nombre Del Árbol '" required=""  value="{{ $tree->name }}" style="margin-left:55%; margin-top: -4.3%">

                            	
                                <button type="submit" id="btnSave" style="margin-top:12%" >Save</button>
                            </form>
                       		 @endforeach  

                       
                    </form>
                </div>
            </div>
        </div>
    </div>



@endsection

resources/views/home.blade.php
@extends('layouts.app')
<style>
            html, body {
                background-image: url('/img/client.jpg');
                font-family: 'Numans', sans-serif;
            }

</style>
@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8"style="margin-left: -28%">
            <div class="card" style="background-color: rgba(0,0,0,0.5); color: #fff; width:140%;    height: 500px;margin-top:2%;">
                <div class="card-header" style="text-align: center; font-size:22px;">Dashboard</div>

                <div class="card-body" >
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                    @if(Auth::user()->admin)
                     <ul class="nav nav-tabs" id="myTab" role="tablist" >
                      <li class="nav-item" >
                        <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">Dashboard</a>
                      </li>
                      <li class="nav-item">
                        <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false">Árboles </a>
                      </li>
                      
                     </ul>
                     <div class="tab-content" id="myTabContent">
                      <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
                        <div class="input-group form-group">
                                <div class="input-group-prepend">
                                    <span class="input-group-text"><i class="fas fa-user"></i></span>
                                </div>
                                 @foreach ($cantUsers as $user)
                                   <p class="name" >Cantidad de amigos registrados: {{$user->cantu}}</p>
                                @endforeach
                        </div>

                        <div class="input-group form-group">
                                <div class="input-group-prepend">
                                    <span class="input-group-text"><i class="fas fa-tree"></i></span>
                                </div>
                                @foreach ($cantTrees as $tree)
                                   <p class="name" > Cantidad de árboles sembrados: {{$tree->cantt}}</p>
                                @endforeach
                        </div>



                      </div>
                      <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">
                          
                        <h2>Árboles Amigos</h2> 
                            <div class="table-wrapper-scroll-y my-custom-scrollbar">
                                <table class="table table-bordered table-striped mb-0 text-center" >
                                    <thead style="color: #FFF;">
                                      <th>#</th>
                                      <th>Name</th>
                                      <th>Height</th>
                                      <th>Owner</th>
                                      <th>Species</th>
                                      <th>View Photo</th>
                                      <th>Actions</th>
                                    </thead>
                                    <tbody style="color: #FFF;">
                                      @foreach ($tableUsers as $table)
                                       <tr>
                                        <td>{{ $loop->iteration }}</td>
                                        <td>{{ $table->name }}</td>
                                        <td>{{ $table->height }}</td>
                                        <td>{{ $table->fullname }}</td>
                                        <td>{{ $table->speciesname }}</td>
                                        <td>
                                             <a href='{{  url('/tree/'.$table->specie_id) }}' class='btn btn-info' style="background-color: rgba(0,0,0,0.5);color: #fff; border: none;">View Photo</a>
                                        </td>
                                        <td>
                                        <a href='{{  url('/tree/'.$table->id.'/edit') }}' class='btn btn-info' style="background-color: rgba(0,0,0,0.5);color: #fff; border: none;">Edit</a>

                                        </td>
                                       </tr>
                                      @endforeach
                                    </tbody>
                                </table>
                            </div>    
                       </div>
                            
                             

                   
                    </div>



                    @else
                    <ul class="nav nav-tabs" id="myTab" role="tablist" >
                      <li class="nav-item" >
                        <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">Dashboard</a>
                      </li>
                      <li class="nav-item">
                        <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false">Árboles </a>
                      </li>
                      
                    </ul>
                    <div class="tab-content" id="myTabContent">
                      <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">

                        <form action="{{ route('tree.store') }}" method="post">
                            @csrf
                            <select name="combo" id="comboEspecies" onchange="" >
                                 <option value="">Selecione una especie de árbol...</option>
                                    @foreach ($species as $specie)
                                        <option value="{{ $specie->id }}">{{ $specie->name }}</option>
                                    @endforeach 
                            </select> 
                            

                            <input type="text" name="nom" id="nom" placeholder=" Nombre " onfocus="this.placeholder = ''" onblur="this.placeholder = 'Nombre '" required="" >
                             

                            <input type="number" id="monto" name="monto" placeholder=" Monto para donar " onfocus="this.placeholder = ''" onblur="this.placeholder = 'Monto para donar  '" required="" > 
                            
                             <button type="submit" id="btnSav">Comprar Árbol</button>
                        </form>




                      </div>
                      <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">
                          
                        <h2>Mis Árboles</h2> 
                            <div class="table-wrapper-scroll-y my-custom-scrollbar">
                                <table class="table table-bordered table-striped mb-0 text-center" >
                                    <thead style="color: #FFF;">
                                      <th>#</th>
                                      <th>Name</th>
                                      <th>Height</th>
                                      <th>Species</th>
                                      <th>Foto</th>
                                    </thead>
                                    <tbody style="color: #FFF;">
                                      @foreach ($trees as $table)
                                       <tr>
                                        <td>{{ $loop->iteration }}</td>
                                        <td>{{ $table->name }}</td>
                                        <td>{{ $table->height }}</td>
                                        <td>{{ $table->speciesname }}</td>
                                         <td>
                                         <a href='{{  url('/tree/'.$table->specie_id) }}' class='btn btn-info' style="background-color: rgba(0,0,0,0.5);color: #fff; border: none;">View Photo</a>
                                        </td>
                                       </tr>
                                      @endforeach
                                    </tbody>
                                </table>
                            </div>    

                         
                       </div>
                            
                             

                      
                    </div>
                    

                        
                      
                @endif
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/index.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="icon" href="{{asset('img/icon.png')}}" type="image/png">
        <title>Un Millón De Árboles</title>
        <!-- Bootstrap CSS -->
        
        <link rel="stylesheet" type="text/css" href="{{asset('bootstraps/css/bootstrap.css')}} ">
        <link rel="stylesheet" type="text/css" 
        href="{{asset('https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css')}}" 
        integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">


        <!--Fontawesome CDN-->
        <link rel="stylesheet" type="text/css"  href="{{asset('https://use.fontawesome.com/releases/v5.3.1/css/all.css')}}" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">

        <!-- Fonts -->
        <link type="text/css"  href="{{asset('https://fonts.googleapis.com/css?family=Nunito:200,600')}}" rel="stylesheet">
       
        <!-- Styles -->
        <style>
            html, body {
                background-color: #fff;
                color: #636b6f;
                font-family: 'Nunito', sans-serif;
                font-weight: 200;
                height: 100vh;
                margin: 0;
            }

            .full-height {
                height: 100vh;
            }

            .flex-center {
                align-items: center;
                display: flex;
                justify-content: center;
            }

            .position-ref {
                position: relative;
            }

            .top-right {
                position: absolute;
                right: 10px;
                top: 18px;
            }

            .content {
                text-align: center;
            }

            .title {
                font-size: 84px;
            }

            .links > a {
                color: #636b6f;
                padding: 0 25px;
                font-size: 13px;
                font-weight: 600;
                letter-spacing: .1rem;
                text-decoration: none;
                text-transform: uppercase;
            }

            .m-b-md {
                margin-bottom: 30px;
            }
        </style>
    </head>
    <body>
     @if (Route::has('login'))
        <nav class="navbar navbar-expand-lg navbar-light bg-light" style="">
        @auth
          <a class="navbar-brand" href="{{ url('/home') }}" >Home</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
        @else  
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
              <li class="nav-item active">
                <a class="nav-link" href="{{ route('login') }}">Login <span class="sr-only">(current)</span></a>
              </li>

            @if (Route::has('register'))
               <li class="nav-item active">
                <a class="nav-link" href="{{ route('register') }}">Register <span class="sr-only">(current)</span></a>
              </li>
            @endif
           @endauth 
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Redes Sociales
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                  <a class="dropdown-item" href="#">Facebook</a>
                  <a class="dropdown-item" href="#">Instagram</a>
                  <a class="dropdown-item" href="#">Twitter</a>
                </div>
              </li>
            </ul>
          </div>
        @endif
            <img class="icon" src="{{asset('img/icon.png')}}" style="height: 80px;width: 80px; margin-right: 100px"/>
        </nav>

        @yield('conten')
        
    </body>
     <!-- jQuery first, then Popper.js, then Bootstrap JS -->
         <script src="{{asset('bootstraps/js/jquery-3.3.1.min.js')}}"></script>
         <script src="{{asset('bootstraps/js/bootstrap.min.js')}}"></script>
        
</html>

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">
     <link rel="icon" href="{{asset('img/icon.png')}}" type="image/png">
     <title>Un Millón De Árboles</title>

   

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">
     <!--Fontawesome CDN-->
     <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link href="{{ asset('css/cliente.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    <img class="icon" src="{{asset('img/icon.png')}}" style="height: 80px;width: 80px; margin-right: 100px"/>
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto" style="font-size: 18px;">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item" >
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name . " " .Auth::user()->lastname }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>

 <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>
    
</html>

resources/views/photo.blade.php
@extends('layouts.app')
<style>
            html, body {
                background-image: url('/img/client.jpg');
                font-family: 'Numans', sans-serif;
            }

</style>

@section('content')

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card"  style="background-color: rgba(0,0,0,0.5); color: #fff; width:110%; height: 110%;margin-top:7%; ">
                <div class="card-header" style="text-align: center; font-size:22px;">{{ __('Edit Tree') }}</div>

                <div class="card-body"style="margin-right:10%; margin-top:4%;">
                             
                            @foreach ($imgs as $img)      
                                
                                <div id="carouselExampleControls" class="carousel slide" data-ride="carousel" >
                                      <div class="carousel-inner" style="height:220px; width:350px;  margin-left: 28%; margin-top:3.5%;">
                                        <div class="carousel-item active" >
                                          <img class="d-block w-100" src="/{{ $img->imgone }}" alt="First slide" style="height:220px; width:450px;">
                                        </div>
                                        <div class="carousel-item">
                                          <img class="d-block w-100" src="/{{ $img->imgtwo }}" alt="Second slide" style="height:220px; width:450px;" >
                                        </div>
                                        <div class="carousel-item">
                                          <img class="d-block w-100" src="/{{ $img->imgthree }}" alt="Third slide" style="height:220px; width:450px;">
                                        </div>
                                      </div>
                                      <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
                                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                                        <span class="sr-only">Previous</span>
                                      </a>
                                      <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
                                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                                        <span class="sr-only">Next</span>
                                      </a>
                                </div>

                       		@endforeach  

                       
                    </form>
                </div>
            </div>
        </div>
    </div>



@endsection